

Automatically generated by Colaboratory.


import pandas as pd
data= pd.read_csv('/content/Tempreture_1901_2016_Pakistan (1).csv')
data

data.info()

data.columns

data[['Temperature - (Celsius)', ' Year' ]].median()

import matplotlib.pyplot as plt

#linegraph
graph= data.head(20)
graph.plot(x='Month', y='Temperature - (Celsius)')

graph= data.head(20)
graph.plot.bar(x='Month', y='Temperature - (Celsius)')

graph= data.tail(20)
graph.plot.barh(x='Month', y='Temperature - (Celsius)')

graph= data.head(20)
graph.plot.scatter(x='Month', y='Temperature - (Celsius)', figsize=(8 ,6))
